variable "customer" {}
variable "environment" {}
variable "owner" {}
variable "vpc_cidr" {}
variable "project" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "domain_name" {}
variable "password" {}
variable "size" {}
variable "customer_dns_ips" {}
variable "customer_username" {}
variable "vpn_routes" {}
variable "ip_address" {}
variable "default_ou" {}
variable "user_volume_size_gib" {}
variable "root_volume_size_gib" {}
variable "running_mode" {}
variable "compute_type_name" {}
variable "bundle_id" {}